apiVersion: v1
kind: ConfigMap
metadata:
  name: facility-config
  namespace: collector
data:
  LOGGING_LEVEL: "info"
  SERVER_PORT: "8081"
  DATABASE_URL: "jdbc:postgresql://192.168.105.150:5432/conpita"
  DATABASE_USERNAME: "conpita"
  DATABASE_DRIVER: "org.postgresql.Driver"
  MQTT_BROKER_URL: "tcp://1.212.76.242:18831"
  MQTT_BROKER_USERNAME: "admin"
  MQTT_BROKER_QOS: 0
  MQTT_BROKER_CONN_TIMEOUT_SEC: 10
  MQTT_BROKER_KEEP_ALIVE_INTERVAL_SEC: 60
  MQTT_BROKER_AUTO_RECONNECT: true
  FACILITY_STATUS_HISTORY_SAVE_ENABLED: false
