apiVersion: v1
kind: Secret
metadata:
  name: facility-secret
  namespace: collector
type: Opaque
data:
  # echo -n 'your-influxdb-token' | base64
  DATABASE_PASSWORD:   bWFzdGVy
  MQTT_BROKER_PASSWORD: YWRtaW4xMjM0
