apiVersion: v1
kind: Service
metadata:
  name: facility
  namespace: collector
  labels:
    app: facility
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  selector:
    app: facility
